CREATE TABLE Cripto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cripto_name TEXT NOT NULL,
    value NUMERIC,
    predicted_value NUMERIC,
    date_now DATE,
    expected_date DATE,
    gain BOOLEAN
);
