CREATE TABLE Payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    plan TEXT,
    bot BOOLEAN,
    api BOOLEAN,
    payment_method TEXT,
    credit_card TEXT,
    debit_card TEXT
);
