CREATE TABLE Tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR NOT NULL,
    token TEXT,
    created_at TIMESTAMP,
    expires_at TIMESTAMP,
    total_requests BIGINT,
    active BOOLEAN,
    status TEXT
);
