CREATE TABLE Users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    full_name TEXT,
    email TEXT,
    phone BIGINT,
    Region TEXT,
    password TEXT,
    type TEXT,
    active BOOLEAN
);
